Repository wecode-bootcamp-korea/21-2nd-GanadaBang-frontend, pull requests merged in 2021-06, with the labels that each got.

#4 [21기 이도윤] ADD:상세페이지 레이아웃 구성 중
  public/data/dummy.json
  src/Pages/Product/Product.js
  src/Pages/Product/Svg/SVG.js
  src/Routes.js
  src/Styles/mixin.js
Labels: Status: 리뷰 요청

#2 [21기 정유정] Nav Modify: code review feedback, menu 타겟팅 되었을 때 다른 style
  .eslintrc
  .gitattributes
  src/Components/MenuButton.js/MenuButton.js
  src/Components/Nav/Nav.js
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#3 [21기 정유정] Footer Add: 레이아웃, styled component
  src/Components/Footer/Footer.js
  src/Routes.js
  src/icons.js
Labels: Status: 리뷰 요청

#5 [21기 정유정] Feature/main 백엔드와 search data 연동
  public/data/mainProductList.json
  public/data/searchFilterData.json
  src/Components/Nav/Nav.js
  src/Components/RecommedProduct/RecommedProduct.js
  src/Components/SearchModal/SearchModal.js
  src/Pages/Main/Main.js
  src/Pages/Product/Product.js
  src/Routes.js
  src/config.js
  src/icons.js
  src/utils/inputOutsideClick.js
Labels: Status: Accepted
