Repository wecode-bootcamp-korea/21-2nd-GanadaBang-frontend, pull requests merged in 2021-07, with the labels that each got.

#6 [21기 김건우] Add : 지도 레이아웃 구현
  .gitignore
  package-lock.json
  package.json
  public/Data/rooms.json
  src/Components/Pagination/Pagination.js
  src/Components/SearchModal/SearchModal.js
  src/Pages/Main/Main.js
  src/Pages/Map/Content/List/Item.js
  src/Pages/Map/Content/ListWrap.js
  src/Pages/Map/Content/MapWrap.js
  src/Pages/Map/MapPage.js
  src/Pages/Map/SubHeader/Filter/Dock.js
  src/Pages/Map/SubHeader/Filter/DockContainer/CheckWrap.js
  src/Pages/Map/SubHeader/Filter/DockContainer/RangeWrap.js
  src/Pages/Map/SubHeader/Filter/DockContainer/input/InputRange.js
  src/Pages/Map/SubHeader/FilterWrap.js
  src/Pages/Map/SubHeader/SearchWrap.js
  src/Routes.js
  src/Styles/theme.js
  src/Util/filterDataSet.js
  src/Util/getTypeName.js
  src/Util/inputOutsideClick.js
  src/Util/useMapPageContext.js
  src/Util/useOutsideClick.js
  src/config.js
  yarn.lock
Labels: Status: 리뷰 요청

#7 [21기 정유정] Modify: LoginModal 백엔드와 연동 완료, 로그인 시 레이아웃 수정
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/KakaoLogin/KakaoLogin.js
  src/Components/LoginModal/LoginModal.js
  src/Components/LogoutModal/LogoutModal.js
  src/Components/Nav/Nav.js
  src/Pages/Map/Content/List/Item.js
  src/Pages/SaleRoom/SaleRoom.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#11 [21기 정유정]최종 백엔드 연동 완료
  src/Components/RecommendProduct/RecommendProduct.js
  src/Pages/Main/Main.js
  src/config.js
  yarn.lock
Labels: Status: 리뷰 요청

#9 [21기 이도윤] Modify: 목데이터를 이용해 화면 구성
  package-lock.json
  public/data/dummy.json
  public/data/dummyRecommen.json
  src/Components/CookieIcon/CookieIcon.js
  src/Components/ListBox/ListBox.js
  src/Pages/Main/Main.js
  src/Pages/Product/MapBox/MapBox.js
  src/Pages/Product/Modal/ModalBox.js
  src/Pages/Product/Product.js
  src/Pages/Product/Svg/SVG.js
  src/Utils/useOutsideClick.js
  src/config.js
Labels: Status: Conflict 해결 요청

#10 [21기 정유정] Add: 방 내놓기 사진 등록 부분 사진 업로드까지만 완료
  package.json
  public/index.html
  src/Components/LoginModal/LoginModal.js
  src/Components/LogoutModal/LogoutModal.js
  src/Components/Nav/Nav.js
  src/Components/RecommendProduct/RecommendProduct.js
  src/Components/SearchModal/SearchModal.js
  src/Pages/Main/Main.js
  src/Pages/Product/MapBox/MapBox.js
  src/Pages/Product/Product.js
  src/Pages/SaleRoom/SaleRoom.js
  src/Routes.js
  src/Utils/useOutsideClick.js
  src/config.js
  src/icons.js
  src/key.js
  yarn.lock
Labels: Status: Conflict 해결 요청, Status: 리뷰 요청, Status: 추가 기능 구현중
